server:
  port: 9090

#配置日志文件输出路径
logging:
  file:
    path: ./logs

spring:
  application:
    name: dev
  #配置mysql数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.130.226:3306/galaxy
    username: root
    password: 123456

mybatis:
  #配置启动mybatis时所需的java bean的路径，用于映射
  type-aliases-package: com.example.bean
  #配置存放sql语句的路径
  mapper-locations:
    - mapper/*